services:
  - type: web
    name: fb-token-extractor
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:$PORT app:app"
    envVars:
      - key: FACEBOOK_API_VERSION
        value: "v19.0"
      - key: PORT
        value: "5000"
